.eslintrc.json
.prettierrc.json
.vscode/settings.json
README.md
package-lock.json
package.json
src/App.js
src/components/Button/BasicButton.js
src/components/ToolBar/ToolBar.js
src/components/ToolBar/ToolBarButton.js
src/components/ToolBar/ToolBarGroup.js
src/components/ToolBar/ToolBarPartition.js
src/components/ToolBar/ToolBarWrapper.js
src/components/Widgets/AllWidgets.js
src/components/Widgets/Image/AddImage.js
src/components/Widgets/Image/Image.js
src/components/Widgets/Video/AddVideo.js
src/components/Widgets/Video/YoutubeVideo.js
src/components/Wrapper/EditWrapper.js
src/components/Wrapper/NormalWrapper.js
src/components/Wrapper/PageWrapper.js
src/components/Wrapper/WidgetWrapper.js
src/components/index.js
src/index.js
src/pages/EditMode.js
src/pages/NormalMode.js
src/pages/index.js
src/reportWebVitals.js
yarn.lock

- vscode 세팅(프로젝트 단위 적용)
- eslint 세팅
- prettier 세팅

chore: 코딩 스타일 통일 위한 환경설정

---

.eslintrc.json
.vscode/settings.json
package-lock.json
package.json
src/components/GridLayout/GridLayout.js
src/components/Widgets/EditAllWidgets.js
src/components/Wrapper/EditWrapper.js
src/components/Wrapper/NormalWrapper.js
src/components/Wrapper/PageWrapper.js
src/components/index.js
src/pages/EditMode.js
yarn.lock

- GridLayout 생성
- EditAllWidget 생성

feat: 그리드 기본적인 기능 세팅

---

.vscode/settings.json
src/components/Button/BasicButton.js
src/components/Header/Header.js
src/components/Header/HeaderWrapper.js
src/components/ToolBar/ToolBar.js
src/components/index.js
src/pages/EditMode.js
src/pages/NormalMode.js

- 저장버튼을 툴바, 헤더에 각각 포함시킴
- css는 임시이므로 추후 수정필요

feat: 수정모드의 툴바와 노멀모드 헤더의 css수정

---

src/components/Widgets/EditAllWidgets.js
src/pages/EditMode.js

- gridLayout.js 수정
- EditAllWidgets.js 수정

feat: 멘토님 드래그 앤 드롭 구현

---

.vscode/settings.json

feat: .vscode setting 변경

---

src/App.js
src/pages/KakaoCallback.js
src/pages/LoginPage.js
src/pages/index.js
src/utils/constantValue.js

feat: add kakao login authorization

---

.eslintrc.json
package-lock.json
package.json
src/App.js
src/pages/EditModePage.js
src/pages/Main.js
src/pages/NormalModePage.js
src/redux/slice.js

- add babel-eslint/
- redux 적용되어 바뀐 코드파일에 표시("여기"). 일요일 컨펌 후 주석 지울 예정.

feat: mark edited part('여기')

---

src/App.js
src/ReduxTest.js
src/redux/slice.js

feat: 리덕스 테스트 코드 추가

---

src/components/GridLayout/EditModeGrid.js
src/components/GridLayout/GridLayout.js

feat: editmode grid height fixed

---

src/components/GridLayout/EditModeGrid.js
src/components/GridLayout/GridLayout.js
src/components/ToolBar/ToolBar.js
src/components/Widgets/Image/AddImage.js
src/components/Widgets/deleteWidgetUtils.js
src/pages/SaveEditPageData.js
src/utils/convert.js

- 프론트에서 widget_code 사용하는 부분을 i 를 대신 사용하도록 수정
- TODO: 서버에 값을 보내도 수정, 삭제가 반영되지 않아 체크 필요함

위젯 생성, 삭제, 수정 관련 리덕스 값 업데이트 완료

---

src/components/GridLayout/Grid.css
src/pages/SaveEditPageData.js
src/utils/convert.js

- react grid rayout 에서 나는 경고 수정(autoSize 삭제)

feat: grid rayout warning 수정

---

src/components/GridLayout/EditModeGrid.js
src/components/ToolBar/ToolBar.js
src/components/Widgets/Image/AddImage.js
src/components/Widgets/WidgetElement.js
src/pages/EditModePage.js
src/pages/SaveEditPageData.js
src/redux/slice.js
src/utils/convert.js

- 서버와 소통 체크(GET, POST 테스트 완료)
- 리덕스에 있는 위젯 배열 중에 widget_action이 'D'인 항목 제외하고 화면에 띄우기 성공
- TODO: 유저 이름을 받아와서 normal 페이지에 적용시키기
- TODO: heom에게 too much re-render error난 부분 설명하기

feat: create, edit, delete 모두 구현

---

src/components/GridLayout/EditModeGrid.js
src/components/Widgets/Image/EditImage.js
src/components/index.js
src/pages/EditModePage.js
src/redux/slice.js

- delete few comments
- EditModeGrid에서 위젯 그리는데 사용할 배열을 새로 만드는 함수에 useCallback 대신에 useMemo를 사용함

EditModeGrid 최적화

---

src/components/Widgets/Image/EditImage.js
src/components/Widgets/Image/ImageBox.js
src/components/Widgets/Image/PopImage.js
src/components/Widgets/Video/PopVideo.js
src/components/Widgets/Video/VideoBox.js
src/components/Widgets/newWidgetUtils.js
src/utils/convert.js

- 프론트엔드에서 사용하던 데이터 구조 수정 (url -> thumbnail, link -> url)

feat: 링크 있는 이미지 클릭시 새탭으로 링크열기 구현

---

.eslintrc.json
src/asset/index.js
src/components/Header/Header.js
src/pages/MainPage.js
src/pages/NormalModePage.js

feat: modify header component to fit main page

---

src/components/Widgets/Image/PopImage.js
src/pages/RenderEditPage.js

- 이미지 데이터 잘 못 업로드 하던 에러를 수정하였습니다.

feat: 이미지업로드 에러

---

src/api/getAccessToken.js
src/components/Header/Header.js
src/components/login/HandleKakaoLogin.js
src/components/login/SaveEditPageData.js
src/pages/MainPage.js
src/pages/RenderLoginPage.js
src/pages/RenderNormalPage.js
src/pages/SaveEditPageData.js

- localhost:3000에서 로그인하면 배포된 url로 리다이렉션되는 문제 해결
- 개발모드와 배포된 모드가 각 다른 리다이렉션 url으로 돌려보내도록 함(로컬 테스트시에는 'X-localhost: true'를 헤더에 넣어서 보냄)
- 로그아웃 버튼 생성

feat: 리다이렉션 uri 수정

---

src/asset/index.js
src/components/Footer.js
src/components/GridLayout/GridLayout.js
src/components/Widgets/Image/PopImage.js
src/components/Widgets/NonType/PopNonType.js
src/components/Widgets/Pop/PopTypeComponent.js
src/components/Widgets/Pop/PopWidgets.js

- 위젯 기본 생성 사이즈 2*2로 수정
- 팝업 상태에서 엔터키 누를 시 모달 닫기
- 구현되지 않은 위젯 클릭 시 모달 디자인 변경

feat: edit모드 위젯 팝업 수정

---

src/components/ToolBar/ToolBar.js
src/components/Widgets/NonType/PopNonType.js
src/components/Widgets/Pop/PopWidgets.js

fix: 인풋 클릭 시 팝업 닫히는 버그

---

package-lock.json
src/components/Header/Header.js
src/components/RenewAccessToken.js
src/components/Widgets/Image/PopImage.js
src/components/Widgets/NonType/PopNonType.js
src/components/Widgets/Video/PopVideo.js
src/components/login/HandleKakaoLogin.js
src/components/login/SaveEditPageData.js
src/pages/MainPage.js
src/pages/RenderEditPage.js
src/pages/RenderNormalPage.js
src/pages/RenderUserName.js
src/pages/SaveEditPageData.js
src/styles/loadingStyle.js
src/styles/popWindowStyle.js

feat: 로딩중 스타일 업데이트

---

src/components/LoadingMessageStyle.js
src/components/RenewAccessToken.js
src/components/Widgets/Image/PopImage.js
src/components/Widgets/NonType/PopNonType.js
src/components/Widgets/PopButtonsWrapper.js
src/components/Widgets/Video/PopVideo.js
src/components/login/HandleKakaoLogin.js
src/pages/RenderEditPage.js
src/pages/RenderNormalPage.js
src/pages/SaveEditPageData.js

#67 src/styles 폴더제거 반영

---

package-lock.json
package.json
src/pages/JoinPage.js
src/pages/SigninRight.js

- 사용자 입력에 대한 가이드 메세지 출력하도록 함 
- 사용자에게 url을 반드시 입력하도록 바꿈
- 랜덤url을 생성할 필요가 없기 때문에 nanoid 설치제거

가이드 메세지 출력부분 코딩

---

src/components/login/HandleKakaoLogin.js
src/hooks/useInput.js
src/pages/JoinPage.js
src/pages/SigninRight.js
src/styles/GlobalStyles.jsx
src/utils/util.js

- JoinPage를 카카오회원가입과 로컬회원가입에 쓸 수 있도
록 처리
- useInput이 컴포넌트를 리턴하도록 리팩토링

 feat: JoinPage 스타일 입힘

---

package-lock.json
package.json
src/components/GridLayout/EditModeGrid.js
src/components/GridLayout/NormalModeGrid.js

- 헤더 변경으로 인해 calc 계산에 오류가 생겨 있었던 문제입니다. 헷갈리는 clac 100%와 100vw 대신 windowWidth를 사용해 통일성을 주어 해결했습니다.

feat: 그리드 위치 계산 정정

---

src/App.js
src/components/Login.js
src/hooks/useInput.js
src/pages/EditModePage.js
src/pages/NormalModePage.js

- widget list를 받아오는 api맞춰봄(get, post)
- normal page와 edit page 모두 테스트

url을 user 시퀀스에서 user가 등록한 URL로 바꾸기 위해 필요한 '/me' 요청 url 보충

---

.eslintrc.json
src/components/login/HandleKakaoLogin.js
src/hooks/useInput.js

fix: useInput에서 overlap 체크를 요청하는 useEffect의 의존성리스트 수정
- 의존성 리스트에 value 추가

fix: 카카오 로그인후 개인 페이지로 리다이렉션 하도록 수정

---

src/components/Widgets/Image/PopImage.js
src/hooks/useRequestAuth.js
src/hooks/widget.js
src/utils/util.js

- 로컬 이미지 업로드 구현완료
- #147 
- 토큰 만료시 저장 안되는 문제 해결
- #149
- popImage 리덕스에 위젯 데이터 저장하는 부분 함수로 분리
- useRequestAuth 리팩토링

토큰 만료시 저장안되는 문제 해결, 로컬업로드 구현

---

src/App.js
src/components/EmailCertModal.js
src/components/GridLayout/EditModeGrid.js
src/components/Login.js
src/components/Widgets/Image/ImageBox.js
src/components/Widgets/Video/PopVideo.js
src/components/Widgets/WidgetElement.js
src/hooks/useInput.js
src/hooks/util.js
src/pages/EmailCertPage.js
src/pages/JoinPage.js
src/pages/NormalModePage.js
src/pages/TermPage.js
src/pages/index.js
src/styles/GlobalStyles.jsx
src/utils/constantValue.js
src/utils/util.js

- 이메일 인증 구현
- 노멀모드 모바일 버전 작업
- 위젯 내부의 버튼 크기 수정

이메일 인증 구현, 노멀모드 모바일 버전 작업

---

src/components/FeedbackBox/FeedbackHeader.js
src/components/Header/Header.js
src/components/login/HandleKakaoLogin.js
src/hooks/widget.js
src/pages/JoinPage.js
src/pages/SplashPage.js

- 회원가입 페이지 email 인증 state가 업데이트 되지 않아 관련 수정

/login을 /main으로 수정

---

src/hooks/useInput.js
src/pages/JoinPage.js
src/pages/NormalModePage.js

- 이메일 인증에 따른 회원가입페이지 제출버튼 disabled 처리를 local 모드에서만 하도록 변경

조인페이지 제출 제한 조건 변경

---

package-lock.json
src/components/Main/MainContents.js
src/components/Wrapper/NormalWrapper.js

- 애니메이션을 px에서 퍼센트로 수정하였습니다.
- 애니메이션이 반복됩니다.

feat: 애니메이션 수정

---

src/components/Header/HeaderWrapper.js
src/components/Wrapper/PageWrapper.js
src/pages/FeedbackPage.js

- margin이 부족하고 min-width가 일괄 적용되지 않아 헤더가 잘리던 부분을 수정하였습니다.

fixed: 헤더가 잘리는 버그 수정

---

src/components/FeedbackBox/FeedbackInputBox.js
src/components/FeedbackBox/FeedbackList.js
src/components/Header/Header.js
src/components/Header/MainHeader.js
src/components/Wrapper/PageWrapper.js
src/hooks/myInfo.js

fixed: 피드백 페이지 로그인 미적용 문제 임시 해결

---

src/components/Widgets/Video/VideoBox.js

유튜브 '공유하기'로 생성된 단축링크로도 위젯 생성가능하도록 수정

---

src/components/Widgets/Video/VideoBox.js

유튜브 쇼츠로도 위젯 추가 가능하도록 변경

---

src/asset/edit_toggle.svg
src/asset/edit_toggle_hover.svg
src/asset/index.js
src/components/Header/Header.js
src/components/Widgets/Video/YoutubeVideo.js
src/components/index.js
src/pages/EditModePage.js
src/pages/NormalModePage.js

- 에딧모드의 헤더가 삭제되었습니다.
- 토클을 통해서 수정과 삭제 버튼을 숨기기가 가능합니다.

feat: 에딧모드(수정모드) 헤더 삭제 및 토글 추가

---

package-lock.json
package.json

secure: 디펜더시 업데이트

---

src/components/GridLayout/EditModeGrid.js
src/components/Widgets/Image/PopImage.js
src/components/Widgets/Video/PopVideo.js
src/hooks/widget.js
src/styles/GlobalStyles.jsx
src/styles/style.js

- 파일 이름이 길면 input 태그 길어지는 문제 -> overflow: hidden으로 해결
- 위젯 생성시 이전 위젯과 겹치는 문제 -> count가 위젯 생성시에만 올라가도록 변경

fixed: 수정페이지 버그 fix

---

public/index.html
src/hooks/setMetaTags.js
src/hooks/widget.js
src/pages/MainPage.js

test: 메타테그 테스트

---

src/App.js
src/components/Join/RightBox.js
src/components/MyPage/AddPagePopUp.js
src/components/MyPage/PageBlock.js
src/components/Widgets/Pop/PopWidgets.js
src/components/Widgets/WidgetElement.js
src/hooks/useRequestAuth.js
src/hooks/util.js
src/hooks/widget.js
src/pages/MyPage.js
src/redux/slice.js

feat: 개인페이지 페이지 정보 간단 통신

---

src/components/FeedbackBox/FeedbackListCol.js

fixed: 피드백 아무것도 없을 떄 기본 색상 값 1번으로

---

src/components/MyPage/Azone.js
src/components/MyPage/PageBlock.js
src/pages/MyPage.js

feat: 메인에 푸시해서 죄송합니다

---

src/components/PublishingPage/MultiPage/MultiHeader.js
src/pages/MultiPage.js
src/pages/MyPage.js
src/pages/PublishingSplitPage.js
src/pages/SinglePage.js
src/utils/convert.js

#235 멀티페이지 라우터 변경 완료

---

src/App.js
src/components/ScrollToTop.jsx
src/components/Widgets/Text/Text.js
src/pages/MyPage.js

#254  텍스트 위젯 null 참조 버그, 페이지 이동 시 스크롤 맨 위로

---

src/components/Header/Header.js
src/components/MyPage/AddPageBlock.js
src/components/MyPage/Bzone.js
src/components/MyPage/PageBlock.js
src/components/MyPage/PageList.js
src/pages/MyPage.js

1. 페이지 없을 시 페이지 생성 버튼 없던 문제 해결
2. 로그아웃 상태 시 페이지 헤더 버튼 안뜨던 문제 해결

fixed: 개인페이지 버그들 수정

---

src/components/MyPage/AddPageBlock.js
src/components/MyPage/Bzone.js
src/components/MyPage/PageList.js

- 페이지 추가 적용 안되는 버그 수정
- 남의 개인 페이지에 페이지가 없을 경우 페이지가 없다는 문구가 뜨도록 변경

fixed: 페이지 추가 안되는 버그 수정

---

src/components/FeedbackBox/MyfeedbackList.js
src/pages/FeedbackPage.js

피드백 갯수가 3개 이하일 경우, css가 깨지던 버그입니당.
slick 옵션을 갯수에 따라서 변경하도록 하여 해결했습니다.
또한 피드백이 없을 경우와 불러오는 중인 경우를 추가하였습니다.

fixed: 피드백 꺠지는 버그 수정

---

src/components/PublishingPage/MultiPage/MultiHeader.js
src/pages/EditModePage.js
src/pages/PublishingSplitPage.js
src/utils/util.js

279 access wrong path bug

---

src/components/Widgets/Text/Text.js

이미 있던 텍스트 위젯이 최초 edit 페이지로 들어왔을 때 수정 모드 + 이동 가능인 버그 수정

[버그] 텍스트 위젯 수정 + 이동 가능 현상

---

src/hooks/useInput.js
src/utils/util.js

한글, 영어, 숫자, 15글자 이하 체크 들어갔습니다.

[버그] 회원가입 닉네임 규칙 적용

---

src/components/GridLayout/EditModeGrid.js
src/components/MyPage/BindingButtonSet.jsx
src/utils/util.js

1. 닉네임 검증 오류
- regex : ^ -  시작지점에 해당 단어 있는지 체크, g - global 모든 글자 체크 후 반환, i - ignore 대소문자 구분x
2. 오타 수정
- 오닛 -> 온잇
3. 코드 순서 변경
- 서순 문제인가 해서 일단 코드 순서만 바꿔봤습니다.

[버그] 닉네임 검증 오류, 오타 수정
